s = set("Patrick")
s.add("Ebere")
s.add(1)
s.add("Dozie")
s.add("Null")
print(f"My set contain {len(s)} list")
print(s)
s.remove("Null")
print("I decided to remove one element")
print(f"I now have {len(s)} elements")
print(s)